### ISSUE TITLE
Specialist Actions used in non-specialist jobs 

### ISSUE THREAD

**Issue by bobsponsler** [doxxx/ffxiv-craft-opt-web#133]
Hello, I am having the issue again where the solver is trying to make me use specialist actions (Specifically "Innovative Touch") on a job that is not a specialist.  I've verified that all specialist actions are unchecked (grey) in the attributes tab. Here is the debug copy you requested:

Seed: 49239, Use Conditions: true

Crafter Actions:
  0: advancedTouch
  1: basicSynth
  2: basicTouch
  3: brandOfEarth
  4: brandOfFire
  5: brandOfIce
  6: brandOfLightning
  7: brandOfWater
  8: brandOfWind
  9: byregotsBlessing
  10: byregotsBrow
  11: carefulSynthesis
  12: carefulSynthesis2
  13: comfortZone
  14: flawlessSynthesis
  15: greatStrides
  16: hastyTouch
  17: ingenuity
  18: ingenuity2
  19: innerQuiet
  20: innovation
  21: makersMark
  22: manipulation
  23: mastersMend
  24: mastersMend2
  25: muscleMemory
  26: nameOfEarth
  27: nameOfFire
  28: nameOfIce
  29: nameOfLightning
  30: nameOfWater
  31: nameOfWind
  32: observe
  33: pieceByPiece
  34: preciseTouch
  35: rapidSynthesis
  36: rumination
  37: standardSynthesis
  38: standardTouch
  39: steadyHand
  40: steadyHand2
  41: tricksOfTheTrade
  42: wasteNot
  43: wasteNot2

**Comment by bobsponsler** [comment]
I was using Google Chrome too - I think this may be a problem with Chrome because it doesn't seem to happen in internet explorer

**Comment by doxxx** [comment]
That's really weird. The solver should only be able to use actions which appear in that list. 

Could you export your settings from the More... menu and attach the zip to this issue? Which recipe are you using? Are you starting from an empty sequence when you run the solver?

**Comment by bobsponsler** [comment]
Hi Gordon,
Sorry for the late reply, I'm behind on checking my email. I think we figured out that there is a problem with google chrome potentially not updating/deleting certain cached information. Recipes were including "innovative touch" no matter what we did to try to remove it. (It seemed to be limited to innovative touch and not the other specialist actions, even when innovative touch was not even in the available actions in the debugger report). My friend and I have each switched to internet explorer and have been using the solver without issue ever since. I'm convinced that this is a problem with Chrome and not with your code. Also, I believe the limit of three specialists is being removed with the upcoming expansion which will allow us to continue working with chrome when the expan is released. Perhaps just a note on the site that warns potential new users that there is a known issue with chrome and that another browser may be advised until the expan comes out? (It otherwise works fine - just that one specialist action). 

Thanks! 

Bob

**Comment by doxxx** [comment]
Support for specialists and specialist actions has been recently updated on the beta site. Let me know if you're still experiencing problems and I'll re-open.

**Comment by doxxx** [comment]
Reopening due to reports of this still happening.

**Comment by belazor** [comment]
I am on my mobile just now, completely fresh data set as I have never used this site on mobile before (iOS 11 Public Beta 1). 

If I enter Lv56 CRP and fill out my data as per the referenced issue, then click By Level, it selects the first 4 specialist actions even though the box is not ticked. 

I’ve turned on debug mode and I’ll try reproducing the issue in the solver.

**Comment by doxxx** [comment]
Oh I see! That sounds like a different issue. The By Level button is only looking the actions levels and isn't ignoring specialist actions for non-specialists.

**Comment by belazor** [comment]
I know, but the issue from the OP _did_ happen to me too. I can’t seem to replicate it just now, I tried without filling in any of the other crafter’s data, and with. I’ll upload my settings dump soon.

**Comment by belazor** [comment]
I can't seem to replicate it right now, but I did find a seed number I was given: 134320

Even manually specifying this seed in the options doesn't appear to reproduce the issue, though. Very strange.

**Comment by doxxx** [comment]
I've deployed a fix to the beta site for the Select By Level button selecting specialist actions for non-specialist classes.

**Comment by Callinon** [comment]
Still happening now. Specifically with Innovative Touch. Additionally the solver will no longer allow specialist actions to be deselected on non-specialist classes. Doing so simply disables the solver altogether.

**Comment by doxxx** [comment]
Well that’s interesting... I’ll take a look.
