### ISSUE TITLE
Simulator allows Muscle Memory outside first step

### ISSUE THREAD

**Issue by Idran** [doxxx/ffxiv-craft-opt-web#358]
Pretty straightforward, this one, and easy to reproduce: The simulator allows/will solve with Muscle Memory anywhere in the ability order, but Muscle Memory can't be used outside the first step of a craft. It does at least not calculate progress from Muscle Memory if it's outside the first step, but the ability can't even be triggered anywhere but right at the start, leading to errors in macros.

**Comment by Idran** [comment]
Correction, the simulator _does_ currently calculate Muscle Memory progress outside the first step as though it's usable anywhere.

**Comment by doxxx** [comment]
I've just checked this and the simulator does not add progress when Muscle Memory is used after step 1. However, it does still allow it to consume CP, which it sounds like is incorrect since the ability is not even usable, correct?

**Comment by Idran** [comment]
Oh, hm; I just tried to reproduce and you're right, it didn't calculate progress. Maybe I misread the log before?

But yes, Muscle Memory can't be triggered at all outside the first step of a craft, so deducting CP shouldn't happen either. It also appears that Reflect has the same problem; it can be included after the first step and will deduct CP (without increasing quality), but in-game it also can't be triggered outside the first action.

**Comment by doxxx** [comment]
Ok, thanks for confirming.

**Comment by doxxx** [comment]
Fix deployed to beta site.

**Comment by Drakonas** [comment]
Can confirm this is still an issue. Any updates on this? http://ffxiv-beta.lokyst.net I am using this site.

This is causing my crafts to fail if I don't notice.

![MuscleMemoryScreenshot](http://mars.whatbox.ca:42424/img/opera_2020-04-07_13-55-12.png)

**Comment by OmegaDragon88** [comment]
Can confirm that it's still doing this in the beta site:

![image](https://user-images.githubusercontent.com/64305896/80317019-91c25b80-8801-11ea-8461-09e6979a4253.png)

**Comment by vlsergey** [comment]
Tried to fix it in #396

**Comment by gr3ger** [comment]
The issue was because the buff from muscleMemory was still applied even though the intial progress wasn't. I've made a very small fix for this in #399
